-- GETENUMML

SELECT 	sysenumeration_id ,ISNULL( (SELECT translatedstring.translation
				FROM dbo.translatedstring
				WHERE translatedstring.language_id = 1
				AND translatedstring.multilanguagestring_id = sysenumeration.description_mlid), 
	ISNULL( (select translatedstring.translation
			from dbo.language
			inner join dbo.translatedstring
				on language.parentlanguage_id = translatedstring.language_id
			WHERE language.language_id = 1
			AND translatedstring.multilanguagestring_id = sysenumeration.description_mlid),
			sysenumeration.description)) as [Description]
INTO #temp_sysenumeration
FROM DBO.sysenumeration


SELECT  
       WORKORDER_ID
      ,ORDERNUMBER
      ,ORDERITEM_ID
      ,CONTRACT_ID
      ,USER_ID
      ,CUSTOMER_ID
      ,SUPPLIER_ID
      ,FLEETVEHICLE_ID
      ,ORDERDATE
      ,AUTHREFERENCE
      ,ENDDATE
      ,DISTANCE AS WORKORDERDISTANCE
      ,STATUS AS WORKORDERSTATUS
      ,STATUSCODE
INTO #TEMP_WO
FROM SUN_WORKORDER       
WHERE STATUS NOT IN ('History','Disapproved') 
AND ORDERDATE > EOMONTH(GETDATE(),-24)
--and AUTHREFERENCE = '173713' -- 'WB00602435'

SELECT PO.ORDERITEM_ID
      ,PO.ORDERITEMNUMBER
      ,PO.ORDERRMTASK_ID
      ,PO.COMPLETIONDATE
      ,PO.APPROVALDATE
      ,PO.SERVICETYPE
      ,PO.DESCRIPTION AS PartBrand
      ,PO.ACTIONONVPGROUP
      ,PO.PARTDESCRIPTION  as CompCategory
      ,PO.SHORTDESCRIPTION
      ,PO.AMOUNTEXCLVAT
      ,PO.AMOUNTINCLVAT
      ,CASE WHEN PO.ACTIONONVPGROUP LIKE '%tyre%' THEN 'TYRE'
            WHEN (PO.ACTIONONVPGROUP LIKE '%service%' OR PO.ACTIONONVPGROUP LIKE '%Maint%') THEN 'MAINTENANCE'
            --WHEN PO.ACTIONONVPGROUP LIKE '%Maint%' THEN 'MAINTENANCE'
            WHEN (PO.ACTIONONVPGROUP LIKE '%repair%' OR PO.ACTIONONVPGROUP LIKE '%Refurb%') THEN 'REPAIR'
            --WHEN PO.ACTIONONVPGROUP LIKE '%Refurb%' THEN 'REPAIR'
            ELSE 'OTHER'
        END MainCategory
INTO #TEMP_POI
FROM #TEMP_WO WO
JOIN PLN_ORDERITEM           PO         on PO.ORDERITEM_ID    = WO.ORDERITEM_ID


SELECT POI.*
--,DBO.GETENUM(D_VP.COMPONENTCLASS)	AS SubCategory
,inct.description AS SubCategory
INTO #TEMP_ORDERITEMS
FROM #TEMP_POI        POI
JOIN ORDERITEM               OI          ON OI.ORDERITEM_ID    = POI.ORDERITEMNUMBER AND OI.ACTIONONVP_ID IS NOT NULL
JOIN [ACTIONONVP]            AVP         ON OI.actiononvp_id = AVP.actiononvp_id AND OI.ACTIONONVP_ID IS NOT NULL
JOIN [VEHICLEPART]           VP          ON AVP.vehiclepart_id = VP.vehiclepart_id AND VP.vehiclepart_id is not NULL
JOIN [D_VEHICLEPART]         D_VP        ON VP.vehiclepart_id = D_VP.vehiclepart_id
left outer join DBO.sysenumeration inct  on inct.sysenumeration_id = D_VP.COMPONENTCLASS

SELECT DISTINCT TOI.* 
      ,ORMT.ORDERRMTASKNUMBER
      ,ORMT.LABOURRATE
      ,ORMT.LABOURCOST
      ,ORMT.CHARGEONAMOUNT
      ,ORMT.LABOURDISCOUNT
      ,ORMT.PARTPRICE
      ,ORMT.PARTDISCOUNT
      ,ORMT.PARTCOST
      --,DBO.GETENUMML(d_rmtask.CHARGEOUTREASON, 1)			AS CHARGEOUTREASON
	  	,a1.description 		AS CHARGEOUTREASON
      ,d_rmtask.SAVINGS
      --,DBO.GETENUMML(d_rmtask.SAVINGSREASON, 1)				AS SAVINGSREASON	
		,b1.description as SAVINGSREASON
	    ,ORMT.QUANTITY
INTO #RMTASKS
FROM #TEMP_ORDERITEMS     TOI 
JOIN MON_ORDERRMTASKS     ORMT        ON ORMT.ORDERRMTASK_ID = TOI.ORDERRMTASK_ID --on PO.ORDERRMTASK_ID        = ORMT.ORDERRMTASK_ID 
JOIN D_ORDERRMTASK        d_rmtask    on d_rmtask.ORDERRMTASK_ID  = ORMT.ORDERRMTASKNUMBER
left outer join #temp_sysenumeration a1  on a1.sysenumeration_id = d_rmtask.CHARGEOUTREASON
left outer join #temp_sysenumeration b1  on b1.sysenumeration_id = d_rmtask.SAVINGSREASON


SELECT DISTINCT A.WORKORDER_ID
,A.USERNAME
,A.TRANSITIONDATE
,A.TRANSITIONSTATUS
INTO #TEMP_APPROVAL_USER
FROM (
      SELECT DISTINCT WO.WORKORDER_ID
      ,USR.IDENTIFICATION AS USERNAME
      ,L.TRANSITIONDATE
      --,DBO.GETENUM(L.TRANSITIONSTATE) AS TRANSITIONSTATUS
	  ,inct.description AS TRANSITIONSTATUS
      ,ROW_NUMBER() OVER (PARTITION BY WO.WORKORDER_ID ORDER BY L.TRANSITIONDATE DESC) RN     
       FROM #TEMP_WO            WO
       JOIN PLN_USER            USR    ON USR.USER_ID     = WO.USER_ID
       LEFT JOIN RELOBJECT R     ON R.OBJECT_ID     = WO.ORDERITEM_ID     AND ( R.SYSREPOBJECT_ID = 266 )
       LEFT JOIN LIFECYCLE L     ON L.LIFECYCLE_ID  = R.LIFECYCLE_ID
	   left outer join DBO.sysenumeration inct  on inct.sysenumeration_id = L.TRANSITIONSTATE
       WHERE L.TRANSITIONSTATE = 306
       --and WO.STATUSCODE = L.TRANSITIONSTATE
       ) A
WHERE A.RN = 1


SELECT DISTINCT C.CONTRACT_ID
      ,C.REFERENCE AS CONTRACTREFERENCE
      ,C.UNITACCOUNT_ID
      ,UA.NAME AS UNITACCOUNTNAME
      ,UA.REFERENCE AS UNITACCOUNTREFERENCE
      ,C.STARTDATE
      ,C.FROMDATE
      ,C.ENDDATE
      ,C.TODATE
      ,PC.TRADINGNAME AS CUSTOMERNAME
      ,FV.FLEETVEHICLE_ID
      ,FV.NATURE
      ,FV.MAKE
      ,FV.MODEL
      ,FV.FIRSTREGISTRATIONDATE
      ,FV.LICENSEPLATE
      ,FV.CHASSISNUMBER
      ,FV.ENGINENUMBER
      ,FV.LASTKNOWNDISTANCE
      ,FV.LASTKNOWNDISTANCEDATE
      ,FV.DESCRIPTION AS MODELDESCRIPTION
      ,C.STATUS
      ,QT.NAME AS QUOTATIONTEMPLATE
      ,LS.PRODUCTCATEGORY
      ,LS.DURATION
      ,LS.DISTANCE
      --,MLS.PRODUCTNAME as LeaseComponentName
INTO #TEMP_CONTRACT_DETAILS
FROM SUN_CONTRACT       C --ON WO.CONTRACT_ID = C.CONTRACT_ID    
JOIN SUN_QUOTE          SQ on SQ.QUOTE_ID = C.QUOTE_ID
JOIN QUOTATIONTEMPLATE  QT On QT.QUOTATIONTEMPLATE_ID = SQ.QUOTATIONTEMPLATE_ID
JOIN PLN_CUSTOMER       PC on PC.CUSTOMER_ID = C.CUSTOMER_ID
JOIN PLN_FLEETVEHICLE   FV on FV.FLEETVEHICLE_ID   = C.FLEETVEHICLE_ID
JOIN PLN_LEASESERVICE   LS on ls.LEASESERVICE_ID = C.LEASESERVICE_ID
--LEFT JOIN MON_LSCOMPONENTS   MLS ON MLS.LSCOMPONENTS_ID = LS.LSCOMPONENTS_ID and MLS.SERVICETYPEGROUPCODE = 1008
LEFT JOIN PLN_UNITACCOUNT UA ON UA.UNITACCOUNT_ID = C.UNITACCOUNT_ID
WHERE C.ISACTIVE = 1


SELECT DISTINCT 
       WO.*
      ,RMT.*
      ,USR.IDENTIFICATION AS USERNAME
      ,L.TRANSITIONDATE
      --,DBO.GETENUM(L.TRANSITIONSTATE) AS TRANSITIONSTATUS
	  ,inct.description AS TRANSITIONSTATUS
      ,AU.USERNAME AS USERNAME_WAITINGFORAPPROVAL
      ,AU.TRANSITIONDATE AS TRANSITIONDATE_WAITINGFORAPPROVAL
      ,AU.TRANSITIONSTATUS AS TRANSITIONSTATUS_WAITINGFORAPPROVAL
      ,S.TRADINGNAME as SupplierName
      ,S.LEGALNAME as SupplierGroup
      ,TCD.CONTRACTREFERENCE
      ,TCD.CUSTOMERNAME
      ,TCD.UNITACCOUNT_ID
      ,TCD.UNITACCOUNTNAME
      ,TCD.UNITACCOUNTREFERENCE
      ,TCD.FROMDATE AS CONTRACT_FROMDATE
      ,TCD.STARTDATE AS CONTRACT_STARTDATE
      ,TCD.ENDDATE AS CONTRACT_ENDDATE
      ,TCD.TODATE AS CONTRACT_TODATE
      ,TCD.STATUS AS CONTRACTSTATUS
      ,TCD.PRODUCTCATEGORY
      ,TCD.QUOTATIONTEMPLATE
      ,TCD.NATURE
      ,TCD.MAKE
      ,TCD.MODEL
      ,TCD.MODELDESCRIPTION
      ,TCD.LICENSEPLATE
      ,TCD.CHASSISNUMBER
      ,TCD.ENGINENUMBER
      ,TCD.FIRSTREGISTRATIONDATE
      ,TCD.DURATION
      ,TCD.DISTANCE AS CONTRACTDISTANCE
      ,TCD.LASTKNOWNDISTANCE
      ,TCD.LASTKNOWNDISTANCEDATE
FROM #TEMP_WO                 WO
JOIN #RMTASKS                 RMT    ON RMT.ORDERITEM_ID   = WO.ORDERITEM_ID
JOIN #TEMP_CONTRACT_DETAILS   TCD    ON TCD.CONTRACT_ID    = WO.CONTRACT_ID
JOIN PLN_SUPPLIER             S      ON S.SUPPLIER_ID      = WO.SUPPLIER_ID  
LEFT JOIN PLN_USER            USR    ON USR.USER_ID        = WO.USER_ID
LEFT JOIN #TEMP_APPROVAL_USER AU     ON AU.WORKORDER_ID    = WO.WORKORDER_ID
LEFT JOIN RELOBJECT           R      ON R.OBJECT_ID        = RMT.ORDERITEM_ID     AND ( R.SYSREPOBJECT_ID = 266 )
LEFT JOIN LIFECYCLE           L      ON L.LIFECYCLE_ID     = R.LIFECYCLE_ID
left outer join DBO.sysenumeration inct  on inct.sysenumeration_id = L.TRANSITIONSTATE
WHERE WO.STATUSCODE = L.TRANSITIONSTATE
AND TCD.CUSTOMERNAME = 'SHOPRITE CHECKERS (PTY) LTD'




DROP TABLE #RMTASKS
DROP TABLE #TEMP_CONTRACT_DETAILS
DROP TABLE #TEMP_APPROVAL_USER
DROP TABLE #TEMP_ORDERITEMS
DROP TABLE #TEMP_WO
DROP TABLE #TEMP_POI
DROP TABLE #temp_sysenumeration
